- name: Add CloudNativePG Helm repository
  ansible.builtin.command:
    cmd: helm repo add cnpg https://cloudnative-pg.github.io/charts

- name: Update Helm repositories
  ansible.builtin.command:
    cmd: helm repo update

- name: Install CloudNativePG operator
  ansible.builtin.command:
    cmd: >
      helm upgrade --install cnpg cnpg/cloudnative-pg
      --namespace cnpg-system
      --create-namespace