name: Ansible CNPG Test

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Kind
        uses: helm/kind-action@v1.9.0

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Install kubectl
        uses: azure/setup-kubectl@v4

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible python3-pip
          pip install kubernetes

      - name: Install Ansible collections
        run: ansible-galaxy collection install -r requirements.yml

      - name: Wait for Kubernetes
        run: kubectl get nodes

      - name: Run operator installation
        run: |
          ansible-playbook -i inventories/local/hosts.yml playbooks/install_operator.yml

      - name: Wait for operator to be ready
        run: |
          kubectl rollout status deployment/cnpg-cloudnative-pg \
            -n cnpg-system --timeout=120s

      - name: Deploy PostgreSQL cluster
        run: |
          ansible-playbook -i inventories/local/hosts.yml playbooks/deploy_cluster.yml

      - name: Validate cluster creation
        run: |
          kubectl get clusters
          kubectl get pods